[package]
name = "trellis"
version = "0.1.0"
authors = ["Jeremy Kaplan <jdkaplan@metagram.net>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
chrono = { version = "0.4", features = ["wasmbind"] }
wasm-bindgen = "0.2"
yew = "0.18"
