databases:
  - engine: PG
    name: db
    num_nodes: 1
    size: db-s-dev-database
    version: "12"
domains:
  - domain: trellis.metagram.net
    type: PRIMARY
name: trellis
region: nyc
jobs:
  - name: migrate
    github:
      branch: main
      deploy_on_push: true
      repo: metagram-net/trellis
    dockerfile_path: Dockerfile-migrate
services:
  - name: trellis-server
    github:
      branch: main
      deploy_on_push: true
      repo: metagram-net/trellis
    dockerfile_path: Dockerfile-server
    routes:
      - path: /api
      - path: /authenticate
    http_port: 8000
    health_check:
      http_path: /.well-known/health-check
static_sites:
  - name: trellis-web
    github:
      branch: main
      deploy_on_push: true
      repo: metagram-net/trellis
    dockerfile_path: Dockerfile-web
    output_dir: /app/dist
    routes:
      - path: /
    index_document: index.html
    catchall_document: index.html
